init:
  - git config --global core.autocrlf input

shallow_clone: true

version: '1.0.{build}'

environment:
  matrix:
    - nodejs_version: '0.10'
    - nodejs_version: '0.12'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm test

build: off

cache:
  - node_modules -> package.json

